### PR TITLE
openstack-neutron: 2014.2-18.3.eayunstack.1.0.1

### PR DESCRIPTION
**Pull request by huntxu**
Signed-off-by: Hunt Xu mhuntxu@gmail.com

### CODE REVIEW

**Comment by zhaochao** [comment]
koji build passed.
testing packages:
http://192.168.2.32/kojifiles/work/tasks/1684/1684/

**Comment by huntxu** [comment]
同样添加了一个修复高优先级issue的新patch，在更新前需要再次打包

**Comment by zhaochao** [comment]
koji build passed.
testing packages:
http://192.168.2.32/kojifiles/work/tasks/1690/1690/

**Comment by huntxu** [comment]
再添加解决一个刚发现的issue的patch，需要再次打包

**Comment by zhaochao** [comment]
koji build passed.
testing packages:
http://192.168.2.32/kojifiles/work/tasks/1709/1709/

**Pull request merged**
