### PR TITLE
openstack-neutron: 2014.2-24.eayunstack.1.1

### PR DESCRIPTION
**Pull request by huntxu**
Signed-off-by: Hunt Xu mhuntxu@gmail.com

### CODE REVIEW

**Comment by zhaochao** [comment]
koji build passed.
testing packages:
http://192.168.2.32/koji/taskinfo?taskID=1598

**Comment by huntxu** [comment]
Updated, re-test and rebuild needed.

**Comment by zhaochao** [comment]
koji build passed.
testing packages:
http://192.168.2.32/kojifiles/work/tasks/1653/1653/

**Comment by huntxu** [comment]
由于我在测试环境上已经将之前的rel 22升级了，所以需要再增加一个rel

**Comment by zhaochao** [comment]
koji build passed.
testing packages:
http://192.168.2.32/kojifiles/work/tasks/1675/1675/

**Comment by huntxu** [comment]
又再次更新了一个patch，修复一个高优先级的issue

**Comment by zhaochao** [comment]
koji build passed.
testing packages:
http://192.168.2.32/kojifiles/work/tasks/1687/1687/

**Comment by huntxu** [comment]
又更新了一个patch，-24未在测试环境中升级，所以照常使用rel 24

**Comment by zhaochao** [comment]
koji build passed.
testing packages:
http://192.168.2.32/kojifiles/work/tasks/1704/1704/

**Pull request merged**
